package com.devpath.backend.service.roadmap;

import com.devpath.backend.dto.roadmap.airoadmap.AIRoadmapResponse;
import com.devpath.backend.dto.roadmap.airoadmap.AIRoadmapTask;
import com.devpath.backend.dto.roadmap.RoadmapResponse;
import com.devpath.backend.entity.Roadmap;
import com.devpath.backend.entity.RoadmapTask;
import com.devpath.backend.entity.TaskPriority;
import com.devpath.backend.entity.User;
import com.devpath.backend.repository.RoadmapRepository;
import com.devpath.backend.repository.RoadmapTaskRepository;
import com.devpath.backend.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class AIRoadmapManagerService {

    private final AIRoadmapService aiRoadmapService;
    private final RoadmapRepository roadmapRepository;
    private final RoadmapTaskRepository roadmapTaskRepository;
    private final UserRepository userRepository;

    public RoadmapResponse generateAndSaveRoadmap(
            String goal,
            String username
    ) {

        AIRoadmapResponse aiRoadmap =
                aiRoadmapService.generateRoadmap(goal);

        User user = userRepository.findByUsername(username)
                .orElseThrow(() ->
                        new IllegalArgumentException("User not found"));

        Roadmap roadmap = Roadmap.builder()
                .title(aiRoadmap.getRoadmapTitle())
                .description("Generated by AI")
                .aiGenerated(true)
                .user(user)
                .build();

        final Roadmap savedRoadmap = roadmapRepository.save(roadmap);

        List<RoadmapTask> tasks = aiRoadmap.getTasks()
                .stream()
                .map(task ->
                        RoadmapTask.builder()
                                .title(task.getTitle())
                                .priority(resolvePriority(task))
                                .estimatedHours(resolveEstimatedHours(task))
                                .dueDate(resolveDueDate(task))
                                .completed(false)
                                .roadmap(savedRoadmap)
                                .build()
                )
                .toList();

        roadmapTaskRepository.saveAll(tasks);

        return RoadmapResponse.builder()
                .id(savedRoadmap.getId())
                .title(savedRoadmap.getTitle())
                .description(savedRoadmap.getDescription())
                .totalTasks(tasks.size())
                .completedTasks(0)
                .progress(0)
                .build();
    }

    private TaskPriority resolvePriority(AIRoadmapTask task) {
        return task.getPriority() == null
                ? TaskPriority.MEDIUM
                : task.getPriority();
    }

    private Integer resolveEstimatedHours(AIRoadmapTask task) {
        if (task.getEstimatedHours() == null) {
            return 0;
        }

        return Math.max(0, Math.min(task.getEstimatedHours(), 500));
    }

    private LocalDate resolveDueDate(AIRoadmapTask task) {
        if (task.getDueInDays() == null || task.getDueInDays() <= 0) {
            return null;
        }

        return LocalDate.now().plusDays(task.getDueInDays());
    }
}
