spring:
  ai:
    openai:
      base-url: http://192.168.0.100:1234/v1
      api-key: dummy
      chat:
        options:
          model: qwen2.5-7b-instruct
          max-completion-tokens: 150


  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${SECRET_KEY}
  expiration: 86400000

server:
  address: 0.0.0.0
  port: ${PORT:8080}
