package com.devpath.backend.service;

import com.devpath.backend.dto.AIRoadmapResponse;
import com.devpath.backend.dto.RoadmapResponse;
import com.devpath.backend.entity.Roadmap;
import com.devpath.backend.entity.RoadmapTask;
import com.devpath.backend.entity.User;
import com.devpath.backend.repository.RoadmapRepository;
import com.devpath.backend.repository.RoadmapTaskRepository;
import com.devpath.backend.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class AIRoadmapManagerService {

    private final AiRoadmapService aiRoadmapService;
    private final RoadmapRepository roadmapRepository;
    private final RoadmapTaskRepository roadmapTaskRepository;
    private final UserRepository userRepository;

    public RoadmapResponse generateAndSaveRoadmap(
            String goal,
            String username
    ) {

        AIRoadmapResponse aiRoadmap =
                aiRoadmapService.generateRoadmap(goal);

        User user = userRepository.findByUsername(username)
                .orElseThrow(() ->
                        new IllegalArgumentException("User not found"));

        Roadmap roadmap = Roadmap.builder()
                .title(aiRoadmap.getRoadmapTitle())
                .description("Generated by AI")
                .aiGenerated(true)
                .user(user)
                .build();

        final Roadmap savedRoadmap = roadmapRepository.save(roadmap);

        List<RoadmapTask> tasks = aiRoadmap.getTasks()
                .stream()
                .map(taskTitle ->
                        RoadmapTask.builder()
                                .title(taskTitle)
                                .completed(false)
                                .roadmap(savedRoadmap)
                                .build()
                )
                .toList();

        roadmapTaskRepository.saveAll(tasks);

        return RoadmapResponse.builder()
                .id(savedRoadmap.getId())
                .title(savedRoadmap.getTitle())
                .description(savedRoadmap.getDescription())
                .totalTasks(tasks.size())
                .completedTasks(0)
                .progress(0)
                .build();
    }
}